version: '2.1'

services:
  angular-ngrx:
    image: johnpapa/angular-ngrx
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js
